### ISSUE TITLE
Titre des tickets générés

### ISSUE THREAD

**Issue by ylephx** [InfotelGLPI/metademands#1]
Bonjour,

Y'a t'il une possibilité de définir dynamiquement le nom du ticket créé via une meta-demande ?
dans l'idéal, j'aimerai dans ma metademande, définir un champ "titre" qui définirait le titre de la demande dans le ticket généré.

Merci d'avance pour votre retour, et votre super travail !

Cordialement,

**Comment by mate-infotel** [comment]
Bonjour @ylephx.

Le développement pour définir dynamiquement le nom du ticket dans une meta demande à été développé. Il sera disponible dans la prochaine release de metademands.

Cordialement.

**Comment by ylephx** [comment]
> Bonjour @ylephx.
> 
> Le développement pour définir dynamiquement le nom du ticket dans une meta demande à été développé. Il sera disponible dans la prochaine release de metademands.
> 
> Cordialement.

Merci beaucoup ! ;)
