### ISSUE TITLE
pb affichage blocs cachés

### ISSUE THREAD

**Issue by CorentinS6** [InfotelGLPI/metademands#101]
Bonjour,

Suite à la maj de metademands 3.2.19 vers 3.3.2, nous rencontrons un problème sur un formulaire. Un champ de type liste déroulante dont la selection des options affiche divers blocs cachés ne fonctionne pas.
Voici la configuration de ce champ :
![image](https://github.com/InfotelGLPI/metademands/assets/4438248/85c26a4f-a935-4a2c-83d2-91ad57ce430d)
![image](https://github.com/InfotelGLPI/metademands/assets/4438248/19267cc7-007e-4478-9c20-07384a1143a0)

J'ai bien supprimé les doublons sur ce champs (il y en avait suite à la mise à jour), et j'ai même supprimé les options et les ai recréé, sans succès.
Aucune erreur / aucun log javascript ou php.

Cordialement

**Comment by tsmr** [comment]
Bonjour
Pourriez-vous m'envoyer le fichier XML (au format txt pour l'uploader sur github)

Merci

**Comment by CorentinS6** [comment]
Bonjour,
Envoyé par mail,
Cordialement
