### ISSUE TITLE
Metademand ne s'affiche pas dans le catalogue de service

### ISSUE THREAD

**Issue by tguichard25** [InfotelGLPI/metademands#103]
Bonjour,

Depuis la version 3.3.4, le catalogue de service affiche une page blanche au lieu de la metademand.
![image](https://github.com/InfotelGLPI/metademands/assets/47602797/f86ff4e6-5921-4c2e-ba38-0dbf075f59f3)

dans l'url en enlevant la categorie, la metademand s'affiche correctement:

![image](https://github.com/InfotelGLPI/metademands/assets/47602797/e9b1fb36-2b84-473a-9e35-08242ecb209e)

**Comment by tsmr** [comment]
Bonjour
Nous venons d'ajouter une nouvelle version du Service Catalog. Ca devrait résoudre la problématique.
