### ISSUE TITLE
Problème balise titre ticket

### ISSUE THREAD

**Issue by zej7106** [InfotelGLPI/metademands#108]
Bonjour,
J'ai un problème avec l'étiquette du ticket.
Dans la version 3.2.19, cela fonctionne toujours comme prévu.
![meta-demand01](https://github.com/InfotelGLPI/metademands/assets/150139220/2f9d6ba1-d1d3-4b52-87eb-d9d7f7862f06)

L'étiquette du ticket sera le champ "Titre".

![meta-demand02](https://github.com/InfotelGLPI/metademands/assets/150139220/a0604661-f667-4577-a5c6-3d4465e5e052)

![image](https://github.com/InfotelGLPI/metademands/assets/150139220/3e364149-251f-4940-a7d8-b909a89afcc9)

Après la mise à jour avec la version actuelle:
![meta-demand03](https://github.com/InfotelGLPI/metademands/assets/150139220/8df3f73c-8a00-49f3-8cdc-0bd0984fd39a)

résultat:
![meta-demand04](https://github.com/InfotelGLPI/metademands/assets/150139220/14954e95-0b1c-41c3-a132-bfd86cfaf18d)

![image](https://github.com/InfotelGLPI/metademands/assets/150139220/77400288-b2c0-4e89-828e-05091527d6b9)

![meta-demands-plugin01](https://github.com/InfotelGLPI/metademands/assets/150139220/048869db-acee-410c-9b7a-3a8df021c2c2)
![meta-demands-plugin02](https://github.com/InfotelGLPI/metademands/assets/150139220/30e963d1-24e8-4a94-baf4-2b994061f889)

![meta-demands05](https://github.com/InfotelGLPI/metademands/assets/150139220/a789af93-e778-4583-95a1-172b92f9703e)
![meta-demands06](https://github.com/InfotelGLPI/metademands/assets/150139220/38dfd6d4-b281-463c-9467-253e1e2bfdab)

Il s'agit d'un nouveau GLPI propre juste pour tester le plugin. Cette erreur se produit également dans notre système de production.

Merci et salutations
János Zergi

**Comment by tsmr** [comment]
See 3.3.10 or open a new ticket
