### ISSUE TITLE
Erreur création sous demande avec des apostrophes dans le nom

### ISSUE THREAD

**Issue by tguichard25** [InfotelGLPI/metademands#110]
Bonjour,

Depuis la version 3.3.6, si le nom de la sous demande comporte une apostrophe, la création du ticket échoue avec le message:
Erreur lors de la création.

Log SQL:

[2023-11-15 09:48:00] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 379
  *** MySQL query error:
  SQL: INSERT INTO `glpi_tickets` (`type`, `itilcategories_id`, `content`, `status`, `actiontime`, `requesttypes_id`, `entities_id`, `name`, `users_id_recipient`, `urgency`, `impact`, `priority`, `users_id_lastupdater`, `date`, `global_validation`, `date_creation`, `date_mod`) VALUES ('2', '317', '<table class=\'tab_cadre_fixe\' style=\'width: 100%;\'><tr><th colspan=\'2\'>Ticket parent</th></tr><tr><td colspan=\'2\'><table class=\"tab_cadre\" style=\"width: 100%;border:0;background:none;word-break: unset;\"><tr class=\"even\"><th colspan=\"10\">Informations sur le salarié</th></tr><tr class=\"odd\"><td class=\"title\" style=\"width: 40%;\">Prénom</td><td>test</td></tr><tr class=\"even\"><td class=\"title\" style=\"width: 40%;\">Nom</td><td>test</td></tr><tr class=\"odd\"><td class=\"title\" style=\"width: 40%;\">Fonction</td><td>test</td></tr><tr class=\"even\"><td class=\"title\" style=\"width: 40%;\">Service</td><td>test</td></tr><tr class=\"odd\"><td class=\"title\" style=\"width: 40%;\">Emplacement</td><td>test</td></tr><tr class=\"even\"><td class=\"title\" style=\"width: 40%;\">Activité</td><td>GIE</td></tr><tr class=\"odd\"><td class=\"title\" style=\"width: 40%;\">Site</td><td>CRAS &#62; SI</td></tr><tr class=\"even\"><td class=\"title\" style=\"width: 40%;\">Date d\'arrivée sur site</td><td>15-11-2023</td></tr><tr class=\"odd\"><th colspan=\"10\">Téléphonie mobile</th></tr><tr class=\"even\"><td class=\"title\" style=\"width: 40%;\">Reprise d\'un poste téléphonique mobile existant?</td><td>Oui</td></tr><tr class=\"odd\"><th colspan=\"10\">Ligne mobile</th></tr><tr class=\"even\"><td class=\"title\" style=\"width: 40%;\">N° de la ligne mobile reprise</td><td>test</td></tr><tr class=\"odd\"><td class=\"title\" style=\"width: 40%;\">Nom ancien utilisateur</td><td>GUICHARD</td></tr><tr class=\"odd\"><th colspan=\"10\">Validation</th></tr><tr class=\"even\"><td class=\"title\" style=\"width: 40%;\">Décisionnaire budgétaire</td><td>GUICHARD</td></tr></table></td></tr></table><br>', '1', '0', '1', '0', 'Arrivée d'un nouveau salarié MOBILE', '0', '3', '3', '3', '1831', '2023-11-15 10:47:58', '1', '2023-11-15 10:47:58', '2023-11-15 10:47:58')
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'un nouveau salarié MOBILE', '0', '3', '3', '3', '1831', '2023-11-15 10:47:58', ' at line 1
  Backtrace :
  src/DBmysql.php:1348                               
  src/CommonDBTM.php:722                             DBmysql->insert()
  src/CommonDBTM.php:1323                            CommonDBTM->addToDB()
  ...place/metademands/inc/metademand.class.php:4007 CommonDBTM->add()
  ...place/metademands/inc/metademand.class.php:2705 PluginMetademandsMetademand->createSonsTickets()
  marketplace/metademands/inc/wizard.class.php:2822  PluginMetademandsMetademand->addObjects()
  marketplace/metademands/inc/wizard.class.php:630   PluginMetademandsWizard::createMetademands()
  marketplace/metademands/inc/wizard.class.php:596   PluginMetademandsWizard::showWizardSteps()
  marketplace/metademands/front/wizard.form.php:584  PluginMetademandsWizard->showWizard()
  public/index.php:82                                require()
  {"user":"1831@srv-glpi-01","mem_usage":"0.169\", 4.88Mio)"}

**Comment by tsmr** [comment]
Hello
Try with 3.3.8 version
