### ISSUE TITLE
Enhancement : edit element from metademands

### ISSUE THREAD

**Issue by tomamplius** [InfotelGLPI/metademands#116]
Add solution to define linked element in a ticket in a metademands

Ajouter un moyen de définir les éléments liés à un ticket dans une metademands

![image](https://github.com/InfotelGLPI/metademands/assets/6951820/38f174a2-c6f0-4c7d-bdee-a0d12ce8b6b0)

**Comment by tsmr** [comment]
Hello
You can already do this : 

![image](https://github.com/InfotelGLPI/metademands/assets/13178158/ebfd23ef-67d8-43cc-965c-48e7f249036c)
