### ISSUE TITLE
Transforming a ticket into a meta-request does not work after 10.0.12.

### ISSUE THREAD

**Issue by JeanBart59** [InfotelGLPI/metademands#118]
Since the installation of GLPI 10.0.12, tickets are no longer transformed into meta requests for post-only accounts. This still works for accounts with higher rights.
This problem seems to be linked to the one that has been dealt with for ticket creation: https://github.com/glpi-project/glpi/issues/16535

**Comment by tsmr** [comment]
See https://github.com/InfotelGLPI/metademands/commit/0311f9388b9968600abf97c3433419a98a8f2fdd
