### ISSUE TITLE
Pb impact/urgence

### ISSUE THREAD

**Issue by CorentinS6** [InfotelGLPI/metademands#119]
Bonjour,

Sur une metademande, nous souhaitons que l'usager puisse rensigner l'impact et l'urgence de cette dernière, comme ceci : 
![image](https://github.com/InfotelGLPI/metademands/assets/4438248/8e661c67-4eec-48c4-a641-aec6175cb694)
avec : 
![image](https://github.com/InfotelGLPI/metademands/assets/4438248/d995f2a6-1045-4578-b107-1ab034e79f03)

A la création du ticket, voici de que cela donne : 
![image](https://github.com/InfotelGLPI/metademands/assets/4438248/3d84d842-ad7f-4610-b957-40053afe04f9)
Et voici notre matrice des priorités : 
![image](https://github.com/InfotelGLPI/metademands/assets/4438248/c7fdd828-8ce9-4231-a955-7815bb8b0aa8)

Pour information, il n'y a rien dans "Champs du ticket père.

Cela ne semble pas être pris en compte.

Cordialement

**Comment by tsmr** [comment]
Hello
Try with 3.3.8 version

**Comment by CorentinS6** [comment]
I can't try, see #129

**Comment by CorentinS6** [comment]
sadly still not working : 
![image](https://github.com/InfotelGLPI/metademands/assets/4438248/50ebb7b2-14a7-44b2-935a-524cf1b687f9)

**Comment by CorentinS6** [comment]
Hello,
same in 3.3.10

**Comment by tsmr** [comment]
avez-vous défini au niveau du champ ceci ?

![image](https://github.com/InfotelGLPI/metademands/assets/13178158/a221d2a6-2f80-432c-a6bc-5fa38952274e)

**Comment by CorentinS6** [comment]
mea culpa, ça fonctionne (en 3.3.10)
