### ISSUE TITLE
"Uncaught ReferenceError: nextPrev is not defined" on metademands valid

### ISSUE THREAD

**Issue by CorentinS6** [InfotelGLPI/metademands#129]
Hello,
There is a bug on metademands 3.3.8, on validate demands
> Browser console :
```
Uncaught ReferenceError: nextPrev is not defined
    onclick https://***/plugins/metademands/front/wizard.form.php?metademands_id=11&step=2:1
wizard.form.php:1:1
    onclick https://***/plugins/metademands/front/wizard.form.php?metademands_id=11&step=2:1
```

**Comment by CorentinS6** [comment]
Also have this js error, when clic on select  or radio option, with hidden fields :
`Uncaught ReferenceError: fixButtonIndicator is not defined
    <anonymous> https://***/plugins/metademands/front/wizard.form.php?metademands_id=4&step=2:4319
    dispatch https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    handle https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    trigger https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    trigger https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    each https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:188
    each https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:188
    trigger https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    <anonymous> https://***/plugins/metademands/front/wizard.form.php?metademands_id=4&step=2:3400
    each https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:188
    each https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:188
    <anonymous> https://***/plugins/metademands/front/wizard.form.php?metademands_id=4&step=2:3383
    each https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:188
    <anonymous> https://***/plugins/metademands/front/wizard.form.php?metademands_id=4&step=2:3382
    each https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:188
    <anonymous> https://***/plugins/metademands/front/wizard.form.php?metademands_id=4&step=2:3380
    dispatch https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    handle https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    trigger https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    trigger https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    each https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:188
    each https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:188
    trigger https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    select https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:218
    select https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:218
    bind https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:218
    invoke https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:218
    trigger https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:218
    trigger https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:218
    _registerResultsEvents https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:218
    invoke https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:218
    trigger https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:218
    bind https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:218
    dispatch https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    handle https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    add https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    <anonymous> https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336 line 207 > eval:767
    prop https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336 line 207 > eval:180
    Oe https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    each https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:188
    each https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:188
    Oe https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    on https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    bind https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:218
    bind https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:218
    u https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:218
    _bindAdapters https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:218
    r https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:218
    select2 https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:225
    each https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:188
    each https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:188
    select2 https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:225
    <anonymous> https://***/plugins/metademands/front/wizard.form.php?metademands_id=4&step=2:2822
    u https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    c https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    setTimeout handler*485/</Deferred/then/o/< https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    l https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    fireWith https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    fire https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    l https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    fireWith https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    ready https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    U https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    485 https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:199
    485 https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:188
    485 https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:188
    n https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:225
    <anonymous> https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:257
    <anonymous> https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:257
    <anonymous> https://***/public/lib/base.min.js?v=93c6c26e76b64765395522690cf2e73619681336:257
wizard.form.php:4319:93
`

**Comment by tsmr** [comment]
Can you give me your metademands (xml) ?
