### ISSUE TITLE
Forcer l'affichage de métademands à la connexion pour un utilisateur en interface standard

### ISSUE THREAD

**Issue by Toinou18** [InfotelGLPI/metademands#148]
Bonjour, 
Pourriez vous me dire si il est possible de orcer l'affichage de métademands à la connexion pour un utilisateur en interface standard.
Merci beaucoup
Antoine F

GLPI 10.0.7
Installation mode: TARBALL
Current language:fr_FR
metademands          Name: Meta-Demandes                  Version: 3.3.10     State: Enabled                                 
Install Method: Marketplace

**Comment by tsmr** [comment]
En interface standard non cela n'est pas possible je pense
