### ISSUE TITLE
Erreur installation 3.3.13

### ISSUE THREAD

**Issue by jbesnard** [InfotelGLPI/metademands#150]
Bonjour,
Suite à l'installation de la version 3.3.12 vers 3.3.13, voici le message du debug :
Uncaught Exception Error: Call to undefined method DB::doQuery() in /var/www/html/glpi/marketplace/metademands/hook.php at line 211

Une idée ?

**Comment by tsmr** [comment]
Quelle est votre version de GLPI ?

**Comment by jbesnard** [comment]
Oups, désolé, GLPI 10.0.8 sur PHP 8.1.29 et UBUNTU 20.04.

**Comment by tsmr** [comment]
Il faut upgrader votre glpi en minimum GLPI 10.0.11 (c'est une nouvelle fonction du coeur)
