### ISSUE TITLE
Les tâches ne fonctionne plus !

### ISSUE THREAD

**Issue by DrCooper06** [InfotelGLPI/metademands#157]
Que ce soit en GLPI 10.0.15 ET 10.0.16 et metademands 3.3.15 et 3.3.16 les tâches ne se créeaient plus dans le ticket créé et le mail reçu ne contient que le chiffre 1 au lieu de la description du ticket 
idem sur docker et BDD vierge. Quelqu'un d'autre rencontre ce problème ?

**Comment by tsmr** [comment]
Hello can you give me an xml export of your metademands for testing it ?

**Comment by QuentinDB66** [comment]
Bonjour,
J'ai toujours le problème avec les taches qui ne se créent plus dans les tickets créés.
GLPI 10.0.17 et Plugin 3.3.18

**Comment by tsmr** [comment]
Have you test my fix ?

**Comment by pivanop** [comment]
No not yet, I tried to change the file with the same name in the /var/www/glpi/plugins/metademands/inc folder but the content seems to be slightly different. Is this the good method to apply the fix?
