### ISSUE TITLE
GLPI version 9.5.5 : impossible to create a new object

### ISSUE THREAD

**Issue by aureliefaci** [InfotelGLPI/metademands#32]
Impossible to create a new object :
![image](https://user-images.githubusercontent.com/57228353/116121130-9ba2c700-a6c0-11eb-8a85-3e7bf23a417c.png)

**Comment by tsmr** [comment]
Hello
I think you have a problem with plugin installation. Can you activate debug mode for check errors ?

**Comment by aureliefaci** [comment]
Hi,

Thanks a lot for your reply.
No problem with the installation I already checked the debug mode and no error message 😟
It works with the previous version of metademands but not the last one.

Regards,

Aurélie



________________________________

**Comment by tsmr** [comment]
Hum, i don't understand why plugin don't let you to select the Object to create..

**Comment by CorentinS6** [comment]
Hello,
Same problem on my instance (GLPI 9.5.5 /  metademands 2.7.6).
The previous patch fix it.
Regards

**Comment by Juju34de7** [comment]
Hi all,
I have an issue on a fresh install of this plugin on GLPI 9.5.5 (on Debian) that might be linked.
when I activate the plugin, I have this error in debug mode:
"Uncaught Exception ParseError: syntax error, unexpected ')' in /var/www/plugins/metademands/inc/metademand.class.php at line 588"

I don't have the issue with version 2.7.5.

Regards,
Julien

**Comment by CorentinS6** [comment]
Hello,
Is it possible to merge this ? Or fix in an other way ?
Regards

> Hum, i don't understand why plugin don't let you to select the Object to create..
> 
> You can test this (comment lines) :
> 
> ```
> diff --git a/inc/metademand.class.php b/inc/metademand.class.php
> index 236ec6d..a432732 100644
> --- a/inc/metademand.class.php
> +++ b/inc/metademand.class.php
> @@ -658,15 +658,15 @@ class PluginMetademandsMetademand extends CommonDBTM {
>        echo "<td>";
>        echo __('Object to create', 'metademands') . "&nbsp;<span style='color:red;'>*</span></td>";
>        echo "<td>";
> -      if ($ID == 0) {
> +//      if ($ID == 0) {
>           $objects    = self::getObjectTypes();
>           $idDropdown = Dropdown::showFromArray('object_to_create', $objects, ['value' => $this->fields['object_to_create']]);
>           Ajax::updateItemOnEvent("dropdown_object_to_create" . $idDropdown, "define_object",
>                                   $CFG_GLPI["root_doc"] .PLUGIN_METADEMANDS_DIR_NOFULL . "/ajax/type_object.php", ['object_to_create' => '__VALUE__']);
> -      } else {
> -         echo self::getObjectTypeName($this->fields['object_to_create']);
> -         echo "<input type='hidden' name='object_to_create' value=\"" . $this->fields['object_to_create'] . "\">";
> -      }
> +//      } else {
> +//         echo self::getObjectTypeName($this->fields['object_to_create']);
> +//         echo "<input type='hidden' name='object_to_create' value=\"" . $this->fields['object_to_create'] . "\">";
> +//      }
>        echo "</td>";
>        echo "<td colspan='2'>";
> ```

**Comment by Riesuu** [comment]
Hello,
II have the same problem with the last version of the plugin, no error message.

GLPI 9.5.6

**Comment by tsmr** [comment]
Can you try ths fix ? https://github.com/InfotelGLPI/metademands/commit/3131f7882000d07128fd07dbc0e0764dd0691d29

**Comment by Riesuu** [comment]
Hello,
it working!thanks

**Comment by CorentinS6** [comment]
Hello,
It's also working for me.
Tank you

**Comment by tsmr** [comment]
ok i close. Thanks
