### ISSUE TITLE
textarea not displaying

### ISSUE THREAD

**Issue by CorentinS6** [InfotelGLPI/metademands#34]
Hello,
We have a visual issue in metademands (v2.7.7, glpi 9.5.5), when displaying a hidden block (no text area displaying, only the toolbar) : 
![image](https://user-images.githubusercontent.com/4438248/120770646-a867d580-c51e-11eb-8f0a-8dba839d5f90.png)

Is this related with one of those alerts in the web browser console ? =>
> The resource from “****/plugins/metademands/front/?v=9.5.5” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).  (from /public/lib/tinymce.min.js)

-> because /plugins/metademands/front/?v=9.5.5 send back a HTTP 403 response.
or

> Uncaught SyntaxError: expected expression, got '||' wizard.form.php:3710:45 
> Uncaught SyntaxError: expected expression, got '||' wizard.form.php:3735:45 

Or thoses php Warning : 

> PHP Warning (2): Undefined array key 0 in /var/www/glpi/plugins/metademands/inc/wizard.class.php at line 1664
> PHP Warning (2): Undefined array key 0 in /var/www/glpi/plugins/metademands/inc/wizard.class.php at line 1664
> PHP Warning (2): Undefined array key 0 in /var/www/glpi/plugins/metademands/inc/wizard.class.php at line 2122
> PHP Warning (2): Undefined array key 0 in /var/www/glpi/plugins/metademands/inc/wizard.class.php at line 2122

This issue seems not to happen in Chrome (we use firefox).

Regards

**Comment by tsmr** [comment]
Can you give me firefox version ?
Have you a reverse proxy (to access GLPI) ?

**Comment by CorentinS6** [comment]
Hello,
Firefox v89 et v78.11.0 ESR.
Yes, Nginx with those configs : 
	

> 	 add_header X-Frame-Options "SAMEORIGIN" always; 
> 	add_header X-Content-Type-Options "nosniff" always;
> 	 add_header X-XSS-Protection "1; mode=block";
> 	 add_header Referrer-Policy "same-origin" always;
> 	 add_header Referrer-Policy "origin-when-cross-origin" always;
>	 proxy_hide_header X-Powered-By;

Regards

**Comment by CorentinS6** [comment]
The thing happen especially after the display of a hidden block (when changing a select field value for instance).

**Comment by CorentinS6** [comment]
Hi
It seems to be a more global issue (glpi level), because the problem comes with others textarea fields with **tinymce** (like with knowledge base items).
Regards
