### ISSUE TITLE
Affichage zone multiple en v2.7.7 ?

### ISSUE THREAD

**Issue by edo78240** [InfotelGLPI/metademands#35]
Bonjour,
J'ai installé le plugin Meta-demandes 2.7.7 sur un glpi 9.5.5 et tout fonctionne bien en dehors d'une fonctionnalité apparue normalement depuis la v2.7.5 'l'affichage en zone multiple'

![image](https://user-images.githubusercontent.com/86117182/122578074-cf142900-d053-11eb-8dcb-0da38c95dbec.png)

Je n'ai pas ce choix dans le type de champs

Merci.

**Comment by edo78240** [comment]
> Bonjour,
> J'ai installé le plugin Meta-demandes 2.7.7 sur un glpi 9.5.5 et tout fonctionne bien en dehors d'une fonctionnalité apparue normalement depuis la v2.7.5 'l'affichage en zone multiple'
> 
> ![image](https://user-images.githubusercontent.com/86117182/122578074-cf142900-d053-11eb-8dcb-0da38c95dbec.png)
> 
> Je n'ai pas ce choix dans le type de champs
> 
> Merci.

Bonjour,
Pas de réponse ? Je suis le seul à avoir ce problème ...
Merci.

**Comment by tsmr** [comment]
Bonjour
Que voulez-vous dire dans "Je n'ai pas ce choix dans le type de champs" ?

Vous ne le trouvez pas ici ?

![image](https://user-images.githubusercontent.com/13178158/125488028-909de89b-1af1-466f-9735-f55b1d0cfbf2.png)

**Comment by edo78240** [comment]
Bonjour,

Merci pour votre réponse, en effet je n'avais pas bien compris le mode de fonctionnement la liste déroulante multiple ....
Par contre il n'est possible d'utiliser que les utilisateurs et les applications ?  Il n'est pas possible d'utiliser les objet GLPI ?

**Comment by tsmr** [comment]
Non pas encore :)

**Comment by tsmr** [comment]
old issue
