### ISSUE TITLE
Uncaught Exception Error: Undefined constant "PLUGIN_METADEMANDS_WEBDIRL"

### ISSUE THREAD

**Issue by jfg** [InfotelGLPI/metademands#39]
Hello,

I have this error in debug mode when i load the page to create a new meta-demand :

Uncaught Exception Error: Undefined constant "PLUGIN_METADEMANDS_WEBDIRL" in /httpdocs/plugins/metademands/inc/metademand.class.php at line 739

Currently, i can't create a new Meta-Demand.

Version: GLPI 10.0.0-rc2

**Comment by tsmr** [comment]
Can you try with master version ? i'ts already corrected.
