### ISSUE TITLE
champs du ticket père, aucun élément

### ISSUE THREAD

**Issue by G6Maker** [InfotelGLPI/metademands#40]
bonjour, je ne parviens pas a obtenir les champs du ticket père dans ma méta demande, j'aurais voulu avoir un accès pour changer le titre.
Il y a t-il une manipulation a faire ?
Merci
![image](https://user-images.githubusercontent.com/10283752/167600223-e60ca4a5-2a9f-4f8f-8d94-f908ec0f54ad.png)
![image](https://user-images.githubusercontent.com/10283752/167600314-e046bd0c-5678-4823-b73a-82f39a622409.png)

**Comment by tsmr** [comment]
Il faut définir le champ Titre comme obligatoire dans le gabarit je pense :)

**Comment by G6Maker** [comment]
D'abord merci pour votre réactivité. 
j'ai maintenant un autre problème sur la version 10 de GLPI avec le plugin en version 3.0.1, lorsque je change le titre avec une balise cela ne fonctionne pas, est ce que j'ai oublier une information également ?
Merci
![image](https://user-images.githubusercontent.com/10283752/167604773-85456a2f-0df8-462d-af39-f6a7e080e37f.png)

**Comment by tsmr** [comment]
Bizarre pour ma part, le ticket généré comporte bien la balise..

**Comment by tsmr** [comment]
old issue
