### ISSUE TITLE
Problème d'affichage de la MetaDemande avec une disposition autre que "Onglets sur la gauche"

### ISSUE THREAD

**Issue by RaphaelVI** [InfotelGLPI/metademands#42]
Bonjour,

J'ai rencontré un problème lors de la création d'une MetaDemande :
Celle-ci a été créée, liée à une catégorie, et apparait bien lors de la sélection de cette catégorie 

![image](https://user-images.githubusercontent.com/38419198/168201433-b03421b9-e18c-4764-89a5-754e93b2ff41.png)
![image](https://user-images.githubusercontent.com/38419198/168201507-986b6229-5d0a-40ab-ade9-7a526e0441fc.png)

Cependant, certains de mes utilisateurs me remontent que la MetaDemande n'apparait pas lors de la sélection de cette catégorie : 
![image](https://user-images.githubusercontent.com/38419198/168201697-2cc0a38c-552a-464f-a327-ec7af53c5351.png)

Leur profil était le même que le mien, ainsi que l'entité
La seule différence notable était dans l'onglet "Personnalisation" de leur profil, la disposition n'étais pas la même 
![image](https://user-images.githubusercontent.com/38419198/168201966-3e673ae4-6803-4ea0-ba45-c7f4b75c5834.png)

Lorsque la disposition choisie est "Séparation Verticale", ou "Vue Classique", la MetaDemande ne s'affiche pas lors de la création d'un ticket

Après avoir changé leur disposition pour "Onglets sur la Gauche", la MetaDemande est bien apparue lors de la sélection de la catégorie

Est-ce un problème de configuration GLPI de ma part ?

**Comment by tsmr** [comment]
Bonjour

Non c'est un bug du coeur de glpi qui n'envoie pas les même informations : 

Vous pouvez essayer de modifier /glpi/pugins/metademands/inc/ticket.class.php : 

```
diff --git a/inc/ticket.class.php b/inc/ticket.class.php
index 9939dbf..bcc6bcd 100644
--- a/inc/ticket.class.php
+++ b/inc/ticket.class.php
@@ -69,8 +69,12 @@ class PluginMetademandsTicket extends CommonDBTM {
     */
    static function emptyTicket(Ticket $ticket) {
       // Metademand redirection on ticket creation
-      if (isset($_REQUEST['id'])
-          && $_REQUEST['id'] == 0
+
+      if (
+      (!isset($_REQUEST['id'])
+          ||
+          (isset($_REQUEST['id'])
+          && $_REQUEST['id'] == 0))
           && isset($_REQUEST['type'])
           && isset($_REQUEST['itilcategories_id'])) {
```

**Comment by Fanch-Aldaron** [comment]
Bonjour,

Je rencontre le même soucis et en effet la modification de la personnalisation de l'affichage perturbe le plugin comme écrit par @RaphaelVI 
@tsmr vous indiqué une modification , pouvez-vous être plus clairce qu'il faut modifié s'il vous plaît ? 
Dans le fichier " /glpi/pugins/metademands/inc/ticket.class.php", j'ai cette vu : 
![image](https://user-images.githubusercontent.com/127228718/223477458-3212ce9a-87b0-4b88-89ed-85eb58582f0e.png)
Que faut-il enlever ou ajouter s'il vous plaît ?

**Comment by tsmr** [comment]
Il faut ajouter

(!isset($_REQUEST['id'])
      ||

**Comment by Fanch-Aldaron** [comment]
La correction fonctionne merci, les meta-demandes s'ouvre maintenant dans n'importe quel affichage
Pouvez-vous sortir une nouvelle version du plugin pour glpi 9.5 avec cette correction s'il vous plaît ?
