### ISSUE TITLE
Problème avec un champ lié à un champ caché

### ISSUE THREAD

**Issue by tguichard25** [InfotelGLPI/metademands#43]
Bonjour,

J'ai créé un champ bouton radio avec deux choix "Choix 1" et "Choix 2".
![image](https://user-images.githubusercontent.com/47602797/168230230-c386ea26-4c4e-4531-afdf-dab6e8ec6f35.png)

En fonction du choix sélectionné, j'ai un nouveau champ qui devient visible "Liste 1" pour le "Choix 1" et "Liste 2" pour le "Choix 2".
![image](https://user-images.githubusercontent.com/47602797/168230474-c3b6071d-0c63-457c-80e4-31d7a0d616ec.png)

Dans la "Liste 1", j'ai un autre champ qui devient visible si une case est coché "Choix Liste 1".
![image](https://user-images.githubusercontent.com/47602797/168230497-b7fe0433-f51f-43d8-bb58-d8d287a8e71b.png)

Si je reviens sur mon "Choix 1" et change en "Choix 2", le "Choix Liste 1" reste visible.
![image](https://user-images.githubusercontent.com/47602797/168230536-718e6de1-9967-48f1-930d-e0baf7f5891a.png)

Y a t-il une astuce ou bien ce n'est pas un comportement normal?

**Comment by tsmr** [comment]
Bonjour

Quelle version du plugin et de glpi plz ?

**Comment by tguichard25** [comment]
Bonjour,

Le plugin en v2.7.9 et glpi en 9.5.7

**Comment by tsmr** [comment]
A retester en v3.3.0
