### ISSUE TITLE
Valeur par défaut Urgence

### ISSUE THREAD

**Issue by tguichard25** [InfotelGLPI/metademands#44]
Bonjour,

Serait-il possible de permettre de choisir la valeur par défaut pour la liste Urgence.

Merci.

**Comment by tsmr** [comment]
Il faut la définir dans le gabarit de ticket associé à la catégorie de la métademande :)

**Comment by tguichard25** [comment]
Bonjour,

Je me suis mal exprimé, quand on ajoute un champ urgence, lors de la saisie de la metademands, l'urgence se positionne sur "très haute". Je voudrais changer l'affichage par défaut.
Mon champ n'étant pas obligatoire, si l'utilisateur ne change pas l'urgence, toutes mes demandes vont avoir en urgence très haute.

**Comment by tsmr** [comment]
Oui c'est bien ca. Tu prédéfinies dans le gabarit associé l'urgence

**Comment by tguichard25** [comment]
Bonjour,

Merci pour l'info, je viens de tester tout est ok.
