### ISSUE TITLE
issue with metademand category

### ISSUE THREAD

**Issue by moalkaabi** [InfotelGLPI/metademands#46]
Hi ,
I have metademand created however, if i select" category " then i click save the category is empty and not showing anything 
![image](https://user-images.githubusercontent.com/8044942/169043684-9c108122-4b79-4a7d-a877-583b13add4b3.png)

its not saving the category

**Comment by tsmr** [comment]
Which version of GLPI & plugins please

**Comment by moalkaabi** [comment]
I'm using GLPI 9.5.5 and  Metademands 2.7.9 and I tired before with 2.7.8 same issue , if I click save , its not saving the category and I dont see any logs in the history
________________________________

**Comment by moalkaabi** [comment]
Hi Team,
even with the latest version of metademand , still I'm facing same issue , the category if  I selected , its not saved and if I select the category manually from the ticket , its disconnecting all the child tickets from the parent ticket

**Comment by tsmr** [comment]
Can you try with master version ?
https://github.com/InfotelGLPI/metademands/archive/refs/heads/master.zip

**Comment by moalkaabi** [comment]
Hi Xavier ,
do you have the non-development version for the below plugin ? in order to check I dont have development environment
________________________________

**Comment by moalkaabi** [comment]
Hi Xavier ,
appreciate if you can provide me with tagged version in order for me to install it

**Comment by moalkaabi** [comment]
Hi Team,
any update? why this issue still appearing with the latest version

**Comment by tsmr** [comment]
Please test 3.3.0
