### ISSUE TITLE
Impossible d'ajouter de photo dans une meta-demande

### ISSUE THREAD

**Issue by r-ow** [InfotelGLPI/metademands#48]
J'utilise GLPI 10.0.1  et je n'arrive pas a ajouter des photos dans le champs text d'une meta-demande. 
J'ai essayer de copier et coller (ctl+v) et j'ai essyer en appuyant le boutton d'ajout de photo, dans les 2 cas rien ne se passe. 
Merci !

**Comment by tsmr** [comment]
Vous devez utiliser le type de champ : Ajouter un document pour uploader une photo et non un champ texte
