### ISSUE TITLE
[GLPI 10.0.1 metademands 3.2.1] Problème d'affichage du formulaire

### ISSUE THREAD

**Issue by KosmosJD** [InfotelGLPI/metademands#52]
Bonjour,

Je rencontre un problème d'affichage de mon formulaire de metademande.

Lorsque le mode panier est activé, mon formulaire s'affiche correctement sur l'écran 
/marketplace/metademands/front/wizard.form.php

Le même formulaire mais sans le mode panier activé est invisible sur le même écran. J'y accède correctement via l'url du type /index.php?redirect=PluginMetademandsWizard_1

Merci par avance de votre retour.

**Comment by tsmr** [comment]
Des erreurs en mode debug ?

**Comment by KosmosJD** [comment]
Bonjour,

Je viens de tester à nouveau à l'instant et le formulaire s'affiche désormais correctement sans que je sache pourquoi. Je vous remercie en tout cas pour votre réponse.
