### ISSUE TITLE
Balise <p> dans la description du ticket

### ISSUE THREAD

**Issue by tguichard25** [InfotelGLPI/metademands#53]
Bonjour,

Dans la description de mes tickets j'ai des balises <p>
GLPI 10.0.2
METADEMANDS 3.2.1

![image](https://user-images.githubusercontent.com/47602797/178263454-6b283822-ed14-4dd2-8736-af11ee2b242e.png)

**Comment by tsmr** [comment]
Les données viennent d'une zone de commentaire du formulaire ?
Quelle option est activée au niveau du champ - Utiliser le texte riche : Oui ou Non ?

**Comment by tsmr** [comment]
Pourriez-vous tester avec le texte riche sur Non ? pour voir si cela a un effet ?

**Comment by tguichard25** [comment]
Le fix ne résous pas mon problème.
Le texte riche sur non ne change rien non plus.
