### ISSUE TITLE
Champ obligatoire masqué quand même requis

### ISSUE THREAD

**Issue by tguichard25** [InfotelGLPI/metademands#56]
Bonjour,

J'ai un problème avec un champ obligatoire masqué et affiché sous condition.
En gros j'ai une question "oui/non" si oui, le champ s'affiche.
Ce champ texte est obligatoire.
Si ma question "oui/non" sur non, je ne peux pas déposer ma demande car champ le champ obligatoire n'est pas remplis alors que la question n'est pas affiché ce qui est normal.
![image](https://user-images.githubusercontent.com/47602797/185916018-02b4dcc7-7776-427a-bf8f-e7519ba6d33b.png)

**Comment by tsmr** [comment]
Résolu en dernière version

**Comment by tguichard25** [comment]
Bonjour,

J'ai toujours le problème dans la dernière version (3.2.19).
