### ISSUE TITLE
Suivi par courriel demandeur.

### ISSUE THREAD

**Issue by tguichard25** [InfotelGLPI/metademands#59]
Bonjour,

J'ai certains utilisateurs qui, lors de la création d'une metademande non pas le suivi par courriel d'activé.
Les utilisateurs ont bien un mail de renseigné dans leur fiche.
J'utilise un champ "Objet GLPI, Utilisateur" utilisé comme demandeur.

**Comment by tsmr** [comment]
A retester avec la version 3.2.8
