### ISSUE TITLE
Metademand pour incident et demande

### ISSUE THREAD

**Issue by tguichard25** [InfotelGLPI/metademands#60]
Bonjour,

J'aimerais savoir si il serait possible d'avoir une metademand pour une catégorie de type incident et une autre metademand pour la même catégorie mais de type demande?

**Comment by tsmr** [comment]
Oui c'est possible.
Par contre il y a un bug qui l'empêche - résolu dans la prochaine version
https://github.com/InfotelGLPI/metademands/commit/60b5b9a2d20f2f5cddf22a57d6372343b4c54018
