### ISSUE TITLE
Pas d'export possible des metademandes

### ISSUE THREAD

**Issue by anythingtodaynet** [InfotelGLPI/metademands#61]
Bonjour,

j'ai utilisé metademands sur une infra GLPI de test pour préparer l'abandon de "formcreator" au profit de "metademands" comme plugin pour la gestion de nos formulaires de création de tickets pour les utilisateurs.
Toutefois, lorsque je me rends sur la demande, cliques sur "export" j'ai la page blanche qui charge, et un échec rien ne se passe.

j'ai activé le mode debug de GLPI, et la page affiche le message suivant : 
![image](https://user-images.githubusercontent.com/97094508/203286071-5cbcb14a-3aba-4d1a-af3c-d5f83448bf87.png)

metademands version 3.2.7 (pas de mise à jour proposées)
GLPI version v10.0.3 (je vais tenter l'upgrade vers la 10.0.5 à tout hasard)
[EDIT: en v10.0.5 après réactivation du plugin metademands, même problématique page blanche et pas de téléchargement]

une idée ? une piste ? j'avais justement bien noté cette possibilité d'import-export pour ne pas avoir à faire 2 fois le travail ha ha :(

D'avance merci pour toute aide !

**Comment by tsmr** [comment]
Bonjour

La correction ici :
https://github.com/InfotelGLPI/metademands/commit/6cf7c280293d236a02aa38f2037bb423d02ab5a1#diff-5ce7d8ebd44af991479a750abc68dc8234e3bef317c625c6a4d466416f00ad3fL5918

**Comment by anythingtodaynet** [comment]
bonjour,
merci beaucoup, il va falloir que j'apprenne à intégrer un commit depuis github, je reviendrais confirmer le correctif.
à très vite.

**Comment by tsmr** [comment]
Bonjour je viens de publier une version 3.2.8
