### ISSUE TITLE
pas d'options pour les champs de type nombre ?

### ISSUE THREAD

**Issue by CorentinS6** [InfotelGLPI/metademands#64]
Bonjour,

Y a-t-il des options pour les champs de type nombre ?

Lorsque je clique sur le bouton "Options +", la page est rechargée, mais rien ne semble se passer.

![image](https://user-images.githubusercontent.com/4438248/204294175-a6ac2882-e5be-47b0-9d9a-39f6947abfb8.png)

Je rate quelque chose ?

actuellement en : GLPI 9.5.11 / metademands 2.7.10
meme comportement sous : GLPI 10.0.5 / metademands 3.2.8

Cordialement

**Comment by tsmr** [comment]
Bonjour Non il n'y a pas d'option disponible.

**Comment by CorentinS6** [comment]
Ok
