### ISSUE TITLE
Afficher l'entité du demandeur dans le titre du ticket créé

### ISSUE THREAD

**Issue by KosmosJD** [InfotelGLPI/metademands#65]
Bonjour,

Je souhaiterais pouvoir affiché automatiquement l'entité du demandeur dans le ticket créé suite à l'utilisation d'un formulaire de metademands.

Soit en utilisant le champs titre du ticket père.
Soit en utilisant un champs avec un remplissage automatique.

Cela est-il possible ?

Bien cordialement,

**Comment by tsmr** [comment]
Ok in 3.3.10 (Balise #entity#)
