### ISSUE TITLE
Pas d'envoi de mail de notification sur les tickets enfants

### ISSUE THREAD

**Issue by WxxxD** [InfotelGLPI/metademands#67]
Bonjour,
lors de la création d'une demande via un formulaire MetaDemand, alors une notification est bien envoyée pour le ticket père, mais aucun des tickets enfants créés automatiquement ne génère de mail de notification.
Aucun log dans le fichier glpi\files\_log\mail.log pour les tickets enfants

Cela fonctionnait correctement avant mise à jour GLPI (10.0.1 vers 10.0.5).

Version GLPI : 10.0.5 (Windows)
Version plugin testé : 3.2.7 et 3.2.13

**Comment by tsmr** [comment]
Pourriez-vous retester avec 10.0.6 et la dernière version du plugin ?

**Comment by eramos13** [comment]
Hello, I have configured the plugin with version 3.2.18 and it does not send a notification to the child tickets, whether they are tickets in a new state or in progress (assigned). I use GLPI 10.0.6.

**Comment by eramos13** [comment]
> Pourriez-vous retester avec 10.0.6 et la dernière version du plugin ?

It only sends mail if the notification is activated, update request, but it would arrive for each action on the ticket, it is not a good solution.

**Comment by WxxxD** [comment]
Bonjour,
je viens de tester avec GLPI 10.0.6 et plugin version 3.2.19 => le problème semble avoir été corrigé, merci !

**Comment by tsmr** [comment]
Bonne nouvelle :)
