### ISSUE TITLE
Bouton radio ne cache pas les bloc

### ISSUE THREAD

**Issue by tguichard25** [InfotelGLPI/metademands#69]
Bonjour,

Avec un champ bouton radio, l'option pour cacher les bloc ne fonctionne pas.
Metademands: 3.2.13
GLPI: 10.0.5

**Comment by CorentinS6** [comment]
Bonjour,
Même problème :
`Same Uncaught SyntaxError: expected expression, got '}'  [wizard.form.php:3119:59]`
Soit ici :                               
`   fixButtonIndicator();});});`
Le problème semble avoir été corrigé ? => https://github.com/InfotelGLPI/metademands/blob/7a275262ad6f6d8f8ec574681f1b3a2b55a192a8/inc/wizard.class.php#L2752
