### ISSUE TITLE
v3.2.15 ne génère pas de ticket

### ISSUE THREAD

**Issue by tguichard25** [InfotelGLPI/metademands#73]
Bonjour,

J'ai effectué la mise à jour sur la version 3.2.15 et depuis les formulaires ne génère plus de ticket.

**Comment by tsmr** [comment]
Des erreurs dans les logs ?

**Comment by tguichard25** [comment]
Non pas d'erreur.

**Comment by tsmr** [comment]
En mode debug ?

**Comment by tguichard25** [comment]
Non plus.
En revanche l'url après avoir envoyé le formulaire me semble étrange:
https://glpi/marketplace/metademands/front/wizard.form.php?metademands_id=170&step=create_metademands

**Comment by tguichard25** [comment]
Est-ce que cela pourrai avoir un rapport avec l'ajout du mode pas a pas?

**Comment by moalkaabi** [comment]
same issue I'm unable to submit the tickets its redirecting to different page now
