### ISSUE TITLE
Affichage des champs masqués dans le ticket généré

### ISSUE THREAD

**Issue by CorentinS6** [InfotelGLPI/metademands#75]
Bonjour,

Je rencontre un problème depuis le passage à glpi 10, avec metademands.

Le ticket généré inclus **tous** les champs de la metademands, même si ces derniers sont masqués. Avant la migration glpi 9.5->glpi 10.0, le ticket généré ne contenait que les champs visibles / utilisés du formulaire metademands.

Cordialement

glpi 10.0.6 / metademands 3.2.16

**Comment by CorentinS6** [comment]
Bonjour,
Merci pour votre retour,
Le changement de ce paramètre ne change pas le comportement observé.
Il semble que certains champs (cachés) soient bien ignorés lors de la génération du ticket, mais que certains champs ne le soient pas. Pour être précis, le ticket généré contient (en plus des champs qu'il est censé contenir) : 
- les champs cachés contenant des valeurs par défaut (exemple : des champs de date)
- les champs cachés de type "Titre de bloc".
Bien cordialement

**Comment by DACRUZPGV** [comment]
Bonjour, 

Nous rencontrons le même problème certains champs cachés ne le sont plus en fonction du type de champs à masquer (information / titre).
Les champs que l'on parvient à masquer sont les champs de type case à cocher ou menu déroulant par exemple. 

De plus avant la passage en v10 il était possible de rendre un champs maqués obligatoire, si celui-ci n'était pas affiché dans le formulaire l'utilisateur n'était pas obligé de le compléter.
En V10 plugin 3.2.19 si un champs maqués est obligatoire, l'utilisateur doit le compléter même si celui-ci n'est pas affiché afin de pouvoir créer le ticket.

Avez-vous une solution à ce bug ? 

Merci par avance

**Comment by tsmr** [comment]
Merci de tester en 3.3.0
