### ISSUE TITLE
Erreur lors de la création

### ISSUE THREAD

**Issue by tguichard25** [InfotelGLPI/metademands#79]
Bonjour,

J'ai une erreur lors de la création d'un ticket.

`[2023-03-24 09:19:31] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_tickets` (`content`, `name`, `type`, `entities_id`, `status`, `locations_id`, `itilcategories_id`, `urgency`, `impact`, `priority`, `users_id_lastupdater`, `users_id_recipient`, `date`, `requesttypes_id`, `global_validation`, `date_creation`, `date_mod`) VALUES ('<table class=\'tab_cadre_fixe\' style=\'width: 100%;\'><tr><th colspan=\'2\'>Application métiers &#62; Sage X3 &#62; Administration demande &#62; Gestion des habilitations &#62; Suppression d\'utilisateur</th></tr><tr class=\'even\'><td class=\'title\'>Personne(s) à contacter</td><td>Tristan GUICHARD</td></tr><tr class=\'odd\'><td class=\'title\'>Numéro de téléphone à contacter</td><td>test</td></tr><tr class=\'even\'><td class=\'title\'>Utilisateur à supprimer</td><td>Test SI</td></tr><tr class=\'odd\'><td class=\'title\'>Fonction de l\'utilisateur</td><td>test</td></tr><tr class=\'even\'><td class=\'title\'>Date effective de désactivation du compte</td><td>24-03-2023</td></tr><tr class=\'odd\'><td class=\'title\'>Commentaire</td><td>test</td></tr><tr class=\'even\'></tr></table>', 'Application métiers > Sage X3 > Administration demande > Gestion des habilitations > Suppression dutilisateur', '2', '0', '1', '2023-03-24', '231', '3', '3', '3', '1831', '1831', '2023-03-24 09:19:31', '1', '1', '2023-03-24 09:19:31', '2023-03-24 09:19:31')
  Error: Data truncated for column 'locations_id' at row 1
  Backtrace :
  src/DBmysql.php:1320                               
  src/CommonDBTM.php:721                             DBmysql->insert()
  src/CommonDBTM.php:1326                            CommonDBTM->addToDB()
  ...place/metademands/inc/metademand.class.php:1941 CommonDBTM->add()
  marketplace/metademands/inc/wizard.class.php:3805  PluginMetademandsMetademand->addObjects()
  marketplace/metademands/inc/wizard.class.php:547   PluginMetademandsWizard::createMetademands()
  marketplace/metademands/inc/wizard.class.php:516   PluginMetademandsWizard::showWizardSteps()
  marketplace/metademands/front/wizard.form.php:668  PluginMetademandsWizard->showWizard()
  {"user":"1831@srv-glpi-01","mem_usage":"0.032\", 7.15Mio)"} `

Il semblerait que le problème soit lié à un champ date.

GLPI 10.0.6
Metademands 3.2.18

**Comment by tsmr** [comment]
Oui c'est bizarre - vous envoyez '2023-03-24' pour spécifier le champ lieu du ticket.

**Comment by tsmr** [comment]
Pourriez-vous me fournir le XML de la métademande ?

**Comment by tsmr** [comment]
Encore le cas en 3.3.0 ?
