### ISSUE TITLE
Problème comportement champs masqués obligatoires

### ISSUE THREAD

**Issue by DACRUZPGV** [InfotelGLPI/metademands#83]
Bonjour, 

Nous souhaitons avoir des champs masqués "obligatoires" qui sont affichés en fonction du besoin de l'utilisateur.

En version V9.5.11 plugin 2.7.9 : 
il est possible de rendre un champs masqué "obligatoire" mais si celui-ci n'est pas affiché, l'utilisateur n'est pas obligé de le compléter pour créer son ticket.

**Exemple de meta-demande en v9.5.11 :** 
deux champs masqués obligatoires si l'on coche la case  "Cpage (DPP)"
![image](https://user-images.githubusercontent.com/107191396/234833936-0523a8c9-b0c6-46f4-a6fb-2add6300ac0f.png)

Ci-dessous la création avec succès de ce même ticket avec les champs masqués obligatoires mais non affichés :
![image](https://user-images.githubusercontent.com/107191396/234833854-717103b7-90bd-43a8-9ab0-3cc37b93b277.png)
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/107191396/234834422-ed7d17a9-dc32-47f6-9ea2-aaf3b319dca5.png)

En V10 plugin 3.2.19, sur la même méta-demande, la case à coche "Cpage (DPP)" n'est pas cochée.
Les champs masqués obligatoire doivent tout de même être complétés pour pouvoir créer le ticket (cf. captures ci-dessous)

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/107191396/234834653-9abc7738-49ab-41ee-b136-83305017e8aa.png)
Après le message " Merci de remplir les champs requis" (à noter : tous les champs visibles et obligatoires sont déjà remplis). 
Lorsqu'on coche la case "Cpage (DPP)" on voit bien que les champs masqués sont en surbrillance et donc attendu  : 
![image](https://user-images.githubusercontent.com/107191396/234837418-4e97a8c0-4b6e-462e-a382-00bce9393548.png)

Avez-vous une solution à ce bug ? 

Merci par avance

**Comment by tsmr** [comment]
Bonjour
Je n'arrive pas à répliquer.
Possible de me fournir le XML de la métademande en GLPI v10 ?

**Comment by DACRUZPGV** [comment]
Bonjour,

Vous trouverez ci-joint deux fichiers xml de métademandes où le problème se pose.

Pour information le XML « création de compte arrivée agent » correspond à une métademande créée initialement depuis GLPI V9.5.11 plugin 2.7.9 puis nous avons copié notre base GLPI PROD dans une base de TEST et fait une montée de version en V10 plugin 3.2.19.

Nous avons également recrée en partie cette métademande depuis GLPI V10 plugin 3.2.19 directement pour écarter un problème lié à l’upgrade de version (2ème XML « création de compte arrivée agent_v2 »).

Merci par avance pour votre aide.

Bien cordialement,


***@***.***

Isabel DA CRUZ
Pôle Système et Réseaux
Direction du Système d’Information
Groupe Hospitalier Paul Guiraud
GHT Psy Sud Paris
54, avenue de la République BP 20065
94806 Villejuif cedex
https://www.psysudparis.fr/
***@***.***<https://www.instagram.com/p/CfZPlv7o_UU/>
***@***.***<https://twitter.com/GH_PaulGuiraud>
***@***.***<https://www.linkedin.com/company/6064215/admin/>



[32F60B8C]<https://centredeservices.psysudparis.fr/>

De : Xavier CAILLAUD ***@***.***>
Envoyé : vendredi 28 avril 2023 14:00
À : InfotelGLPI/metademands ***@***.***>
Cc : DA CRUZ Isabel ***@***.***>; Author ***@***.***>
Objet : Re: [InfotelGLPI/metademands] Problème comportement champs masqués obligatoires (Issue #83)

ATTENTION: Ce courriel provient d'une personne externe à votre organisation. Ne cliquez pas sur les liens ou n'ouvrez pas les pièces jointes si vous ne connaissez pas l'expéditeur et que vous n'êtes pas sûr du contenu.

Bonjour
Je n'arrive pas à répliquer.
Possible de me fournir le XML de la métademande en GLPI v10 ?

**Comment by DACRUZPGV** [comment]
Bonjour,

Désolée pour le délai de réponse, effectivement, vous trouverez ci-joints les formulaires correspondant aux captures écrans de l'issue.

Le problème se pose sur tous nos formulaires appelant des champs masqués obligatoires.

Merci par avance pour votre aide.


Cordialement,


Isabel DA CRUZ


<https://centredeservices.psysudparis.fr/>

________________________________
De : Xavier CAILLAUD ***@***.***>
Envoyé : vendredi 28 avril 2023 19:07
À : InfotelGLPI/metademands ***@***.***>
Cc : DA CRUZ Isabel ***@***.***>; Author ***@***.***>
Objet : Re: [InfotelGLPI/metademands] Problème comportement champs masqués obligatoires (Issue #83)


ATTENTION: Ce courriel provient d'une personne externe à votre organisation. Ne cliquez pas sur les liens ou n'ouvrez pas les pièces jointes si vous ne connaissez pas l'expéditeur et que vous n'êtes pas sûr du contenu.

Apparemment les fichiers joints ne sont pas liées à l'issue.

**Comment by tsmr** [comment]
Bonjour

En fait il faut rendre obligatoire les autre champs dans les options (et pas par défaut) : 

il faut utiliser cette option : 

![image](https://github.com/InfotelGLPI/metademands/assets/13178158/5a9f6504-e8fc-4a49-8e89-86726e3a0eb3)

et désactiver le caractère obligatoire des champs Cpage DPP Profils et Cpage DPP Catalogue

**Comment by DACRUZPGV** [comment]
Bonjour, 

Merci pour votre retour rapide, nous allons modifier nos formulaires en conséquence.

Bonne journée,
