### ISSUE TITLE
Continuer une métademande

### ISSUE THREAD

**Issue by enguerrandadeline** [InfotelGLPI/metademands#85]
Bonjour, j'aimerais savoir s'il est-il possible de faire remplir une métademande par plusieurs personnes avant de créer un ticket.
Je pensais qu'en activant le panier, nous pourrions enregistrer une demande dans le panier, et de pouvoir continuer la métademande par une autre personne après.
Merci d'avance de votre aide.
Cordialement,

**Comment by tsmr** [comment]
Bonjour
Il faut activer le Mode "Pas à Pas" - nouvelle fonctionnalité, et définir quel groupe peut remplir quel bloc. Nous sommes en train d'améliorer d'ailleurs cette fonctionnalité.

**Comment by enguerrandadeline** [comment]
Bonjour, je l'avais déjà activé, malheureusement pas de possibilité de faire remplir par une autre personne.

**Comment by tsmr** [comment]
Amélioré en 3.3.0 - a retester
