### ISSUE TITLE
Intégration du plugin gestion d'objet dans meta demands / Generic objects integration in Metademands

### ISSUE THREAD

**Issue by KosmosJD** [InfotelGLPI/metademands#86]
Bonjour,

Serait il possible que le plugin gestion d'objet soit compatible avec meta demands ?
Le but serait de pouvoir sélectionner les objets créés dans gestion d'objet dans l'écran de configuration d'un champs (liste déroulante Objet pour le type Objet GLPI).

Actuellement aucun des éléments créé dans gestion d'objets n'apparait dans cette liste.

Merci.

Bien cordialement,

![GLPIobjects_List](https://github.com/InfotelGLPI/metademands/assets/108822327/46112429-19f4-441e-8101-4ef6999042e4)

Hi,

Would it be possible to integrate generic objects in metademands ? I would like to select the objects created in generic objects in the Object list in the field configuration screen.

Thanks.

**Comment by EC2311** [comment]
Hello
I created a personnal plugin : I don't see its main classes in metademand. (they appear in formcreator)
I think main tables (classes) of any plugins should be recognized by metademand

**Comment by smurdza** [comment]
Hi @tsmr

Can you declare some date, when this enhancement will be work on new wersion plugin.
I thing it is important for all community.

**Comment by tsmr** [comment]
I think it will be easily with next version of GLPI which integrate this plugin into core

**Comment by tsmr** [comment]
https://github.com/InfotelGLPI/metademands/releases/tag/3.3.15
