### ISSUE TITLE
Une meta-demande avec plusieurs catégories, problème à l'affichage de la catégorie dans le ticket créé

### ISSUE THREAD

**Issue by DACRUZPGV** [InfotelGLPI/metademands#87]
Bonjour, 

Nous souhaitons avoir une seule métademande pour plusieurs catégories, il est possible de sélectionner plusieurs catégories.

![image](https://github.com/InfotelGLPI/metademands/assets/107191396/9c08530f-b38c-4bf5-93ef-f37a89962305)

Nous ajoutons ensuite le champs nécessaire "Catégorie de la métademande". 

![image](https://github.com/InfotelGLPI/metademands/assets/107191396/72d69a0a-dc2f-4cd2-8551-9a40756c68b0)

A la création du ticket le formulaire se présente bien à la sélection des catégories, le champs Catégorie de la métademande est prérempli. Toutefois lorsqu'on valide le ticket, le champs "catégorie" du ticket est vide.

![image](https://github.com/InfotelGLPI/metademands/assets/107191396/7695096f-4735-4c63-a5eb-aae6eaff36b4)

Nous souhaiterions que ce champs reprenne la catégorie de la métademande. 

Merci par avance pour votre aide.

**Comment by DACRUZPGV** [comment]
Bonjour, 

Merci pour votre retour, toutefois, nous avons appliqué le fix au fichier metademande.class.php mais notre problème demeure.

Merci par avance de votre aide.

**Comment by redam** [comment]
Même problème de notre côté et le fix est bien présent.
