### ISSUE TITLE
Pas de création de ticket avec servicecatalog

### ISSUE THREAD

**Issue by tguichard25** [InfotelGLPI/metademands#88]
Bonjour,

Sur le dernière version 3.3.0, après avoir remplis le formulaire depuis le plugin servicecatalog, aucune création de ticket ne fonctionne.
En passant directement par le formulaire pas de soucis.

GLPI 10.0.8.

**Comment by tsmr** [comment]
Bonjour

Je viens de sortir la version 3.3.0 de façon officielle - pourriez-vous retester ?

https://github.com/InfotelGLPI/metademands/releases/tag/3.3.0

**Comment by tsmr** [comment]
Quelle version de service catalog ?

**Comment by tguichard25** [comment]
2.0.7

**Comment by tsmr** [comment]
Dans la configuration des 2 plugins il y a un vérificateur de schéma. Les schémas sont-ils bons ?

**Comment by tguichard25** [comment]
servicecatalog schema ok
metademands: https://pastebin.com/RB7GcbkF

**Comment by tsmr** [comment]
Pas de champs manquants en tout cas.

pas de doublons trouvés dans "Outils" de la configuration de metademands ?

Il faudrait peut-être aussi essayer de Régénerer la liste des catégories dans "Outils" dans servicecatalog ?

**Comment by tguichard25** [comment]
J'ai beaucoup de doublon.
J'ai test de Régénerer la liste des catégories mais sans succès.

**Comment by tsmr** [comment]
Pourriez-vous déjà nettoyer les doublons ?

**Comment by tguichard25** [comment]
Je veux bien mais j'avoue avoir du mal a comprendre de quel doublon on parle.

**Comment by tguichard25** [comment]
![image](https://github.com/InfotelGLPI/metademands/assets/47602797/8341fc6f-6318-4efe-9be2-abd79e2ef065)

Est-ce que ça veut dire que j'ai deux champ "Nature du compte" dans le formulaire?

**Comment by tguichard25** [comment]
J'ai compris, c'est des doublons dans les options du champ.
Je fait le ménage

**Comment by tguichard25** [comment]
Toujours pareil après nettoyage des doublons.

**Comment by tsmr** [comment]
Je ne sais pas trop quoi vous dire. Il faudrait regarder si il y a des logs ou des erreurs dans la console du navigateur

**Comment by tguichard25** [comment]
Je pense avoir trouver, j'ai mis a jour ma version de php en 8.2, j'étais en 7.4.
Après update de php, ça fonctionne de nouveau.
Merci pour votre temps.

**Comment by tsmr** [comment]
Nickel :)
