### ISSUE TITLE
Image illisible dans un champs "Zone de texte"

### ISSUE THREAD

**Issue by Sauron59** [InfotelGLPI/metademands#89]
Bonjour,

Je rencontre un bug avec le plugins Meta demande, dans mes formulaires j'ai ajouté un champs "Zone de texte" et si un utilisateur colle l'image directement dans ce champs, nous ne pouvons pas voir cette image

![image](https://github.com/InfotelGLPI/metademands/assets/138863134/02c1425a-2c1d-475d-8a24-6dac2f71b2c1)

Merci pour votre aide et votre travail

**Comment by tsmr** [comment]
Bonjour

Quelle version du plugin ?

**Comment by Sauron59** [comment]
Je suis en version 3.2.19 avec un GLPi en version 10.0.7

**Comment by tsmr** [comment]
:)
