### ISSUE TITLE
Default page

### ISSUE THREAD

**Issue by tomaskanevicius** [InfotelGLPI/metademands#90]
Good afternoon,

After clicking on the tab "Assistance -> Metademands" this tab opens "http://ххх.111/plugins/metademands/front/metademand.php"
![image](https://github.com/InfotelGLPI/metademands/assets/62842018/5e997932-4589-4fe4-8b7f-c600d78c101e)

This information is completely unnecessary for the technician, as he does not configure the requests, but can only fill them in. In this case the technician only has the right to read the request. In order to fill in a request, he has to click on the "Create a demand" tab. 

Is it possible to make it so that after clicking on the tab "Assistance -> Metademands", it would automatically redirect to the page . it would automatically redirect to the page http://ххх.111/plugins/metademands/front/wizard.form.php?

GLPI version 10.6

Metademands version 3.2.13

**Comment by tsmr** [comment]
Hello

Please retry with last version of this plugin for verification

**Comment by tomaskanevicius** [comment]
Just tried the newest version 3.3.0, same problem. 
![image](https://github.com/InfotelGLPI/metademands/assets/62842018/39f95b1e-3e79-40f3-91d9-15088f20c841)

After clicking on the tab "Assistance -> Metademands" this tab opens 
[http://ххх.111/plugins/metademands/front/metademand.php
![image](https://github.com/InfotelGLPI/metademands/assets/62842018/a2a4a0b9-b530-4c72-bc46-64dcdfa33125)

**Comment by tomaskanevicius** [comment]
Can you confirm that this feature will be included in the plugin?
