### ISSUE TITLE
3.3.0 : manque option pour champ 

### ISSUE THREAD

**Issue by CorentinS6** [InfotelGLPI/metademands#91]
Bonjour,

Il manque la possibilité d'ajouter des options aux champs de type : liste déroulante / Objet : catégorie de metademandes (	Utiliser comme champ de l'objet : catégorie)
![image](https://github.com/InfotelGLPI/metademands/assets/4438248/1ae8d804-6de5-4590-a0cc-152b185d7779)

Cordialement

glpi 10.0.9 / metademands 3.3.0

**Comment by tsmr** [comment]
Bonjour
C'est normal je pense, il n'y a pas d'options supplémentaires disponibles pour ce type de champ - a part définir la catégorie de ticket

**Comment by CorentinS6** [comment]
Bonjour,
Le capture d'écran ci dessus vient de notre preprod (glpi 10.0.9 / metademand 3.3.0).
Pour ce type de champ, il y avait bien les options en 3.2.19. Voici une capture du même champ sur notre prod actuelle (glpi 10.0.7 / metademands 3.2.19) : 
![image](https://github.com/InfotelGLPI/metademands/assets/4438248/d19456df-cedb-4b12-b823-d9c9f9384c5f)
Cordialement

**Comment by avallano2817** [comment]
Bonjour,
Il s'avère aussi qu'il n'est plus possible de mettre plusieurs options pour la même réponse.
C'est gênant quand plusieurs champs ou actions découlent de la même réponse.
![image](https://github.com/InfotelGLPI/metademands/assets/129841155/bcb455b1-35c4-4c25-b77c-300394145364)

**Comment by tsmr** [comment]
@avallano2817 merci d'ouvrir une nouvelle issue. Merci

**Comment by tsmr** [comment]
@CorentinS6 Moi j'ai bien l'onglet Option quand je vais dans la fiche du champ.

![image](https://github.com/InfotelGLPI/metademands/assets/13178158/b0d7e795-dc97-4f76-be35-52d138cf83d4)

**Comment by CorentinS6** [comment]
Bonjour,
J'ai identifié les problèmes :
1) je n'avais pas vu l'onglet "options" ;)
2) la migration semble avoir créé des doublon dans les options, ce qui a mis le basard dans l'affichage des blocs cachés.
Problème reglé en ce qui me concerne.

**Comment by tsmr** [comment]
DAns la configuration du plugin, vous pouvez identifier les doublons avec l'onglet "Outils"
