### ISSUE TITLE
Logo sur PDF généré par le plugin

### ISSUE THREAD

**Issue by avallano2817** [InfotelGLPI/metademands#93]
Bonjour,

Comment modifier le logo sur le PDF généré par la Metademande.

Peut-on poussé plus loin la personnalisation de ce document ?

Cordialement.

**Comment by tsmr** [comment]
Bonjour il faut remplacer le fichier metademands/pics/login_logo_glpi.png

Pas plus de personnalisation prévu (ou développement dédié)

**Comment by avallano2817** [comment]
Merci
