### ISSUE TITLE
Champs Masqués

### ISSUE THREAD

**Issue by avallano2817** [InfotelGLPI/metademands#94]
Bonjour,

Depuis la version 3.3.1 l'option "Lier a un champ caché" ne fonctionne plus. 

J'ai désactiver et réactiver le plug-in, je l'ai désinstaller, j'ai redémarré mon Linux mais cela ne change rien. 

Cordialement.

**Comment by tsmr** [comment]
Bonjour

Merci d'essayer avec la version 3.3.2 - https://github.com/InfotelGLPI/metademands/releases/tag/3.3.2

**Comment by avallano2817** [comment]
Bonjour,

On est daccord que remplacer le dossier dans /var/www/html/plugins met a jour le plugin ?

Car j'ai DL le lien que vous m'avez fait passé et rien n'a bougé même pas le numéro de version affiché dans GLPI.

Ya t'il une manip de plus a faire ?

**Comment by avallano2817** [comment]
Bonjour, le correctif 3.3.2 du Market place a bien corrigé l'affichage des champs masqués.

**Comment by tsmr** [comment]
:)
