### ISSUE TITLE
Screenshoot 

### ISSUE THREAD

**Issue by Makrix78** [InfotelGLPI/metademands#95]
Bonjour, Serait-il possible de mettre en place un stockage pour les screenshoots directement incorporés dans le ticket. En effet, ça devient problématique d'avoir des [image] dans beaucoup de nos tickets. Merci

**Comment by tguichard25** [comment]
Bonjour,
De mon côté je n'avais plus le problème en 3.3.1 mais de nouveau en 3.3.2.

**Comment by tsmr** [comment]
Oups désolé. Corrigé :P

**Comment by Makrix78** [comment]
Dans mon cas précis, je parlais des screenshoots copié/collé directement dans le ticket depuis metademands. De mémoire, nous avons toujours eu les images en [image] dans les tickets reçus. Serait-il possible de faire comme les tickets classiques natifs à GLPI ? Merci pour votre réactivité :)

**Comment by tsmr** [comment]
Oui c'est bien cela
