### ISSUE TITLE
Champs caché non disponible dans les options

### ISSUE THREAD

**Issue by RaphaelVI** [InfotelGLPI/metademands#96]
Bonjour,

Je rencontre un problème avec le plugin :

J'ai un champs "Type de matériel" étant de type "Case à cocher" et je souhaiterai afficher un champs caché "Test" si la valeur est "Écran", mais ce champs "Test" n'apparait pas dans la liste :

Voici les libellé créés sur le formulaire : 
![image](https://github.com/InfotelGLPI/metademands/assets/38419198/0b9056e0-30c4-4899-bf6f-5d7bd1c7ef94)

et comme vous pouvez le voir, le champs n'apparait pas :
![image](https://github.com/InfotelGLPI/metademands/assets/38419198/154221ea-9e15-4d85-bb32-bf01029a19c8)
![image](https://github.com/InfotelGLPI/metademands/assets/38419198/1b7ba2df-1493-4d6c-b973-99f86a37a06f)

Par contre, si j'ajoute un nouveau champs "Test2", le champs "Test" apparaît, mais pas le champs "Test2"
![image](https://github.com/InfotelGLPI/metademands/assets/38419198/58c2da34-196e-45ee-9ed9-884c68dfe524)

![image](https://github.com/InfotelGLPI/metademands/assets/38419198/011f1787-c8ed-4d8d-9447-c71887691fb2)

Comment faire ?

Metademan v3.3.0
GLPI v10.0.8

**Comment by tsmr** [comment]
Bonjour
Merci de passer en dernière version du plugin déjà :)

**Comment by Makrix78** [comment]
Hello, concernant les champs cachés, nous avons également un problème en version 3.3.2.
Sur certains de nos formulaires, nous avons des champs qui ne sont plus cachés. 
Exemple : le champ "Lenteur réseau" doit s'afficher uniquement si zscaler est choisi dans "selection de l'application" 
<img width="532" alt="image" src="https://github.com/InfotelGLPI/metademands/assets/140716576/36044361-d819-484a-826c-e5b77c9f8a64">

Nous avons egalement ces deux messages en mode debug, si ça peut être utile ? : 
<img width="662" alt="image" src="https://github.com/InfotelGLPI/metademands/assets/140716576/ba6a6376-7e62-44de-9a3f-19b054a28720">

Et enfin voici le XML de la meta-demande : 
[XML.txt](https://github.com/InfotelGLPI/metademands/files/12230859/XML.txt)

Je te remercie pour les patchs sur les screenshoots et les balises ça fonctionne parfaitement !  👍

**Comment by RaphaelVI** [comment]
Bonjour,
Malheureusement, même après la mise à jour en dernière version, le problème est toujours présent

**Comment by tsmr** [comment]
A retester avec https://github.com/InfotelGLPI/metademands/releases/tag/3.3.3
