### ISSUE TITLE
Problème balise titre ticket 

### ISSUE THREAD

**Issue by Makrix78** [InfotelGLPI/metademands#97]
Bonjour, depuis la passage en version 3.3.2, certaines balises de titre de ticket ne s'affiche plus : 
nous avons des #4# etc.. dans nos titres. Cela n'arrive que sur certains formulaires. J'ai bien vérifié dans les méta-demande que nous utilisions les bonnes balises 
De plus, nous ne pouvons pas lire les screenshoots intégrés dans les tickets, nous ne voyons que des [image] dans nos tickets.

Merci pour votre aide

Version GLPI 10.0.3

**Comment by tsmr** [comment]
Pour les balises je vais regarder. Pourriez-vous m'envoyer un XML de votre métademande concernée ?

Pour les screenshots : 
https://github.com/InfotelGLPI/metademands/commit/8555509c4719deecc2b3c7b3a8202c32930860b1

**Comment by Makrix78** [comment]
Bien sûr :) 

[XML.txt](https://github.com/InfotelGLPI/metademands/files/12227464/XML.txt)

Je tiens à signaler que j'ai testé cette meta-demande avec une autre balise ("description de l'incident") et que cela fonctionne, je vois donc pas trop où ça bloque. (pour "Sélection de l'application") 

<img width="386" alt="image" src="https://github.com/InfotelGLPI/metademands/assets/140716576/a10efa7c-38f9-424a-8858-d9981b80aa27">

Pour les screens, je vais essayé ça tout suite merci !
