### ISSUE TITLE
Step by Step Blocks

### ISSUE THREAD

**Issue by lyemilie** [InfotelGLPI/metademands#98]
Bonjour,
Lorsque j'active la fonction "step by step blocks" et que je le configure, les tickets ne se créent pas et du coup cela ne passe pas au step 2 car on ne voit pas de tickets.
Pouvez-vous m'aider svp ?

**Comment by tsmr** [comment]
Bonjour pourriez-vous me donner la version de GLPI et du plugin ?

**Comment by lyemilie** [comment]
Bonjour,
Ma version de GLPI est 10.0.6 et le plugin de Metademands est 3.3.2.
Je vous remercie pour votre aide !

**Comment by tsmr** [comment]
Pouvez vous m'envoyer le XML de votre metademands ? (renommer le en .txt pour pouvoir l'inclure sur github)

**Comment by avallano2817** [comment]
Il faut faire un export de la Metademands.
Sur le premier onglet de votre metademands, en bas a droite ce trouve un bouton "Export".

Cordialement.

**Comment by lyemilie** [comment]
Merci @avallano2817 !
Voici : 
[metademands_Nouvelle arrivée.txt](https://github.com/InfotelGLPI/metademands/files/12252471/metademands_Nouvelle.arrivee.txt)

**Comment by tsmr** [comment]
A retester avec https://github.com/InfotelGLPI/metademands/releases/tag/3.3.3

**Comment by lyemilie** [comment]
> A retester avec https://github.com/InfotelGLPI/metademands/releases/tag/3.3.3

Bonjour, 

J'ai mis à jour le plugin et réessayer, ça ne fonctionne pas. 

Quand la première personne qui a fini de remplir son BLOC 1 et envoie le formulaire au groupe suivant, il ne reçoit pas le formulaire dans ses tickets..

Merci pour votre aide

**Comment by lyemilie** [comment]
Bonjour, 
Après une recherche, j'ai trouvé d'où vient le problème : 
le bouton "Continuer une métademande" se trouve dans Assistance > Meta-demands. Sauf qu'il faut avoir un profil spécifique afin d'avoir accès à ce profil. N'y a-t-il pas un moyen de mettre le bouton "continuer une métademand" dans l'onglet "Plugin > Meta-demands" ?
